# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remoteControlSignWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignsWidget(object):
    def setupUi(self, SignsWidget):
        SignsWidget.setObjectName("SignsWidget")
        SignsWidget.resize(522, 621)
        SignsWidget.setMaximumSize(QtCore.QSize(522, 621))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SignsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(SignsWidget)
        self.label.setMinimumSize(QtCore.QSize(500, 500))
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/gestureIds.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(SignsWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_rep = QtWidgets.QLineEdit(SignsWidget)
        self.lineEdit_rep.setObjectName("lineEdit_rep")
        self.horizontalLayout_3.addWidget(self.lineEdit_rep)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(SignsWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_gestures = QtWidgets.QLineEdit(SignsWidget)
        self.lineEdit_gestures.setObjectName("lineEdit_gestures")
        self.horizontalLayout_2.addWidget(self.lineEdit_gestures)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_cancel = QtWidgets.QPushButton(SignsWidget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.button_send = QtWidgets.QPushButton(SignsWidget)
        self.button_send.setObjectName("button_send")
        self.horizontalLayout.addWidget(self.button_send)
        self.button_sendRecord = QtWidgets.QPushButton(SignsWidget)
        self.button_sendRecord.setObjectName("button_sendRecord")
        self.horizontalLayout.addWidget(self.button_sendRecord)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(SignsWidget)
        QtCore.QMetaObject.connectSlotsByName(SignsWidget)

    def retranslateUi(self, SignsWidget):
        _translate = QtCore.QCoreApplication.translate
        SignsWidget.setWindowTitle(_translate("SignsWidget", "Form"))
        self.label_3.setText(_translate("SignsWidget", "Repetition number : "))
        self.lineEdit_rep.setText(_translate("SignsWidget", "6"))
        self.label_2.setText(_translate("SignsWidget", "Sequence : "))
        self.lineEdit_gestures.setText(_translate("SignsWidget", "2 7 23 19"))
        self.button_cancel.setText(_translate("SignsWidget", "Cancel"))
        self.button_send.setText(_translate("SignsWidget", "Send exercice"))
        self.button_sendRecord.setText(_translate("SignsWidget", "Send + start recording"))
