# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remoteControlFreemoveWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FreemoveWidget(object):
    def setupUi(self, FreemoveWidget):
        FreemoveWidget.setObjectName("FreemoveWidget")
        FreemoveWidget.resize(422, 394)
        FreemoveWidget.setMinimumSize(QtCore.QSize(422, 394))
        FreemoveWidget.setMaximumSize(QtCore.QSize(422, 394))
        self.verticalLayout = QtWidgets.QVBoxLayout(FreemoveWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_freemove0 = QtWidgets.QPushButton(FreemoveWidget)
        self.button_freemove0.setMinimumSize(QtCore.QSize(400, 50))
        self.button_freemove0.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.button_freemove0.setFont(font)
        self.button_freemove0.setAutoFillBackground(False)
        self.button_freemove0.setAutoRepeat(False)
        self.button_freemove0.setAutoDefault(False)
        self.button_freemove0.setFlat(False)
        self.button_freemove0.setObjectName("button_freemove0")
        self.verticalLayout.addWidget(self.button_freemove0)
        self.button_freemove1 = QtWidgets.QPushButton(FreemoveWidget)
        self.button_freemove1.setMinimumSize(QtCore.QSize(400, 50))
        self.button_freemove1.setMaximumSize(QtCore.QSize(400, 50))
        self.button_freemove1.setObjectName("button_freemove1")
        self.verticalLayout.addWidget(self.button_freemove1)
        self.button_freemove2 = QtWidgets.QPushButton(FreemoveWidget)
        self.button_freemove2.setMinimumSize(QtCore.QSize(400, 50))
        self.button_freemove2.setMaximumSize(QtCore.QSize(400, 50))
        self.button_freemove2.setObjectName("button_freemove2")
        self.verticalLayout.addWidget(self.button_freemove2)
        self.button_freemove3 = QtWidgets.QPushButton(FreemoveWidget)
        self.button_freemove3.setMinimumSize(QtCore.QSize(400, 50))
        self.button_freemove3.setMaximumSize(QtCore.QSize(400, 50))
        self.button_freemove3.setObjectName("button_freemove3")
        self.verticalLayout.addWidget(self.button_freemove3)
        self.button_freemove4 = QtWidgets.QPushButton(FreemoveWidget)
        self.button_freemove4.setMinimumSize(QtCore.QSize(400, 50))
        self.button_freemove4.setMaximumSize(QtCore.QSize(400, 50))
        self.button_freemove4.setObjectName("button_freemove4")
        self.verticalLayout.addWidget(self.button_freemove4)
        self.button_freemove5 = QtWidgets.QPushButton(FreemoveWidget)
        self.button_freemove5.setMinimumSize(QtCore.QSize(400, 50))
        self.button_freemove5.setMaximumSize(QtCore.QSize(400, 50))
        self.button_freemove5.setObjectName("button_freemove5")
        self.verticalLayout.addWidget(self.button_freemove5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_cancel = QtWidgets.QPushButton(FreemoveWidget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.button_send = QtWidgets.QPushButton(FreemoveWidget)
        self.button_send.setObjectName("button_send")
        self.horizontalLayout.addWidget(self.button_send)
        self.button_sendRecord = QtWidgets.QPushButton(FreemoveWidget)
        self.button_sendRecord.setObjectName("button_sendRecord")
        self.horizontalLayout.addWidget(self.button_sendRecord)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FreemoveWidget)
        QtCore.QMetaObject.connectSlotsByName(FreemoveWidget)

    def retranslateUi(self, FreemoveWidget):
        _translate = QtCore.QCoreApplication.translate
        FreemoveWidget.setWindowTitle(_translate("FreemoveWidget", "Form"))
        self.button_freemove0.setText(_translate("FreemoveWidget", "1"))
        self.button_freemove1.setText(_translate("FreemoveWidget", "2"))
        self.button_freemove2.setText(_translate("FreemoveWidget", "3"))
        self.button_freemove3.setText(_translate("FreemoveWidget", "4"))
        self.button_freemove4.setText(_translate("FreemoveWidget", "5"))
        self.button_freemove5.setText(_translate("FreemoveWidget", "6"))
        self.button_cancel.setText(_translate("FreemoveWidget", "Cancel"))
        self.button_send.setText(_translate("FreemoveWidget", "Send exercice"))
        self.button_sendRecord.setText(_translate("FreemoveWidget", "Send + start recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FreemoveWidget = QtWidgets.QWidget()
    ui = Ui_FreemoveWidget()
    ui.setupUi(FreemoveWidget)
    FreemoveWidget.show()
    sys.exit(app.exec_())
